nrniv: syntax error
 near line 2
 a ++ 2
    ^
nrniv: sqrt argument out of domain
 near line 5
 sqrt(-1)
         ^
nrniv: syntax error
 near line 2
 a ++ 2
    ^
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
nrniv: syntax error
 near line 14
 b ++= 2
     ^
nrniv: syntax error
 near line 17
 }
 ^
nrniv: sqrt argument out of domain
 near line 26
 }
  ^
nrniv: syntax error
 near line 14
 b ++= 2
     ^
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
      execute("xopen("tes...")
nrniv: execute error: xopen("test2.hoc")
 in test2.hoc near line 3
 ^
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
      execute1("xopen("tes...")
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
      execute1("{xopen("te...")
    load_file(1, "test2.hoc")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
      execute("xopen("tes...")
nrniv: execute error: xopen("test3.hoc")
 in test3.hoc near line 15
 ^
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
      execute1("xopen("tes...")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
      execute1("{xopen("te...")
    load_file(1, "test3.hoc")
nrniv: syntax error
 in test5.hoc near line 11
 a ++ 2
    ^
        xopen("test5.hoc")
      xopen("test5.hoc")
    xopen("test5.hoc")
  xopen("test5.hoc")
and others
nrniv: syntax error
 in test5.hoc near line 11
 a ++ 2
    ^
        xopen("test5.hoc")
      xopen("test5.hoc")
    xopen("test5.hoc")
  xopen("test5.hoc")
and others
nrniv: execute error: xopen("test5.hoc")
 in test5.hoc near line 13
 ^
nrniv: syntax error
 in test5.hoc near line 11
 a ++ 2
    ^
        xopen("test5.hoc")
      xopen("test5.hoc")
    xopen("test5.hoc")
  xopen("test5.hoc")
and others
nrniv: syntax error
 in test5.hoc near line 11
 a ++ 2
    ^
        xopen("test5.hoc")
      xopen("test5.hoc")
    xopen("test5.hoc")
  xopen("test5.hoc")
and others
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
      execute("xopen("tes...")
nrniv: execute error: xopen("test2.hoc")
 in test2.hoc near line 3
 ^
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
      execute1("xopen("tes...")
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
      execute1("{xopen("te...")
    load_file(1, "test2.hoc")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
      execute("xopen("tes...")
nrniv: execute error: xopen("test3.hoc")
 in test3.hoc near line 15
 ^
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
      execute1("xopen("tes...")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
      execute1("{xopen("te...")
    load_file(1, "test3.hoc")
nrniv: syntax error
 in test5.hoc near line 11
 a ++ 2
    ^
        xopen("test5.hoc")
      xopen("test5.hoc")
    xopen("test5.hoc")
  xopen("test5.hoc")
and others
nrniv: syntax error
 in test5.hoc near line 11
 a ++ 2
    ^
        xopen("test5.hoc")
      xopen("test5.hoc")
    xopen("test5.hoc")
  xopen("test5.hoc")
and others
nrniv: execute error: xopen("test5.hoc")
 in test5.hoc near line 13
 ^
nrniv: syntax error
 in test5.hoc near line 11
 a ++ 2
    ^
        xopen("test5.hoc")
      xopen("test5.hoc")
    xopen("test5.hoc")
  xopen("test5.hoc")
and others
nrniv: syntax error
 in test5.hoc near line 11
 a ++ 2
    ^
        xopen("test5.hoc")
      xopen("test5.hoc")
    xopen("test5.hoc")
  xopen("test5.hoc")
and others
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
      execute("xopen("tes...")
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
      execute1("xopen("tes...")
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        xopen("test2.hoc")
      execute1("{xopen("te...")
    load_file("test2.hoc")
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        execute("//syntax e...")
nrniv: syntax error
 in test2.hoc near line 2
 a ++ 2
    ^
        execute1("//syntax e...")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
      execute("xopen("tes...")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
      execute1("xopen("tes...")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        xopen("test3.hoc")
      execute1("{xopen("te...")
    load_file("test3.hoc")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        execute("// valid m...")
nrniv: syntax error
 in test3.hoc near line 14
 b ++= 2
     ^
        execute1("// valid m...")
nrniv: syntax error
 in test6.hoc near line 13
 a ++ 2
    ^
        xopen("test6.hoc")
      xopen("test6.hoc")
    xopen("test6.hoc")
  xopen("test6.hoc")
and others
Traceback (most recent call last):
  File "test6.py", line 3, in test6
    h.xopen("test6.hoc")
RuntimeError: hoc error
nrniv: PyObject method call failed: test6
 in test6.hoc near line 8
 ^
        xopen("test6.hoc")
      xopen("test6.hoc")
    xopen("test6.hoc")
  xopen("test6.hoc")
Traceback (most recent call last):
  File "test6.py", line 3, in test6
    h.xopen("test6.hoc")
RuntimeError: hoc error
nrniv: PyObject method call failed: test6
 in test6.hoc near line 8
 ^
        xopen("test6.hoc")
      xopen("test6.hoc")
    xopen("test6.hoc")
Traceback (most recent call last):
  File "test6.py", line 3, in test6
    h.xopen("test6.hoc")
RuntimeError: hoc error
nrniv: PyObject method call failed: test6
 in test6.hoc near line 8
 ^
        xopen("test6.hoc")
      xopen("test6.hoc")
Traceback (most recent call last):
  File "test6.py", line 3, in test6
    h.xopen("test6.hoc")
RuntimeError: hoc error
nrniv: PyObject method call failed: test6
 in test6.hoc near line 8
 ^
        xopen("test6.hoc")
Traceback (most recent call last):
  File "test6.py", line 5, in <module>
    test6()
  File "test6.py", line 3, in test6
    h.xopen("test6.hoc")
RuntimeError: hoc error
>>> 
